name: 'Publish wheels to anaconda.org'
description: 'Publish wheels to anaconda.org and optionally clear out old wheels'
branding:
  icon: package
  color: blue
inputs:
  anaconda_user:
    description: Anaconda.org user or organisation
    required: true
    default: ''
    type: string
  anaconda_package:
    description: Anaconda.org package
    required: true
    default: ''
    type: string
  anaconda_token:
    description: Anaconda.org token
    required: true
    default: ''
    type: string
  keep_n_latest:
    description: If specified, only this number of the most recent versions are kept
    required: true
    default: ''
    type: number
runs:
  using: "composite"
  steps:

  - uses: conda-incubator/setup-miniconda@v2

  - name: Upload to Anaconda.org
    run: |
      conda install --yes anaconda-client
      anaconda --token ${{ inputs.anaconda_token }} upload \
        --user ${{ inputs.anaconda_user }} \
        dist/*
    shell: bash -l {0}

  - name: Install click
    run: pip install click

  - name: Clean up old wheels on Anaconda.org
    run: |
      python ${{ github.action_path }}/remove_old_wheels.py \
        --token ${{ inputs.anaconda_token }} \
        --user ${{ inputs.anaconda_user }} \
        --package ${{ inputs.anaconda_package }} \
        --keep ${{ inputs.keep_n_latest }}
    shell: bash -l {0}
